/* Hover/focus glossary for the scientific terms on this page.
 *
 * WHY THIS RUNS AT LOAD RATHER THAN BEING BAKED INTO THE HTML. Most of
 * index.html is regenerated by 14_build_candidate_panels, so any <span> markup
 * written into the page would be wiped on the next rebuild and would have to be
 * re-applied in build order. Annotating text nodes at runtime sidesteps that
 * entirely: the page stays clean and diffable, the glossary lives in one file,
 * and adding a term is a one-line edit here.
 *
 * ONLY THE FIRST MENTION IN EACH SECTION IS MARKED. Marking every occurrence of
 * a word like "docking" would turn the page into a field of dotted underlines
 * and make the marks worthless as a signal. First-per-section means a reader
 * meets each term marked once, close to where they need it.
 *
 * Every entry has a definition AND an analogy, because the two do different
 * jobs: the definition is what the term means, the analogy is what it is like.
 * A reader who bounces off one usually gets the other.
 */
(function () {
  'use strict';

  var TERMS = {
    'molecular glue degrader': ['A small molecule that sticks two proteins together which would not normally meet — one of them a ligase that destroys things — so the other one gets destroyed.', 'Double-sided tape that fixes an unwanted object to the conveyor belt running into the shredder.'],
    'molecular glue': ['A small molecule that makes two proteins stick together that otherwise would not. Some glues cause degradation; others just hold things together.', 'Not a lever or a lid — just glue between two objects that were never meant to touch.'],
    'E3 ubiquitin ligase': ['The enzyme that attaches ubiquitin tags to a protein, marking it for destruction. CRBN is the part of this machine that chooses the victim.', 'The clerk in a sorting office who decides which parcels get a "destroy" sticker.'],
    'ubiquitinated': ['Tagged with ubiquitin — condemned. The cell’s standard way of marking a protein for destruction.', 'Having the disposal label stuck on you.'],
    'ubiquitin': ['A small protein the cell attaches to other proteins as a label. A chain of them is the standard "destroy this" signal.', 'A luggage tag. One means "reroute"; a string of them means "incinerate".'],
    'proteasome': ['The cell’s protein shredder — a barrel-shaped machine that chops up proteins carrying a ubiquitin tag.', 'The paper shredder the tagged documents get fed into.'],
    'cereblon': ['The protein CRBN. It is the part of a larger destruction machine that decides which protein gets destroyed, and it is where thalidomide-class drugs bind.', 'The socket; the drug is an adapter that lets an unexpected plug fit.'],
    'CRBN': ['Cereblon — the substrate receptor of a CRL4 E3 ligase. It picks which protein gets tagged for destruction, and it is where thalidomide-class drugs bind.', 'The socket; the drug is an adapter that lets an unexpected plug fit.'],
    'neosubstrate': ['A protein that an E3 ligase destroys only because a drug is present. Not one of its natural targets.', 'A parcel that only gets the "destroy" sticker because someone slipped the clerk a bribe.'],
    'degron': ['A signal built into a protein that marks it for destruction.', 'A "dispose of me" label the cell can read.'],
    'glutarimide': ['The ring in thalidomide-class compounds that plugs into CRBN’s pocket, imitating the natural degron signal. Every candidate here keeps it unchanged.', 'The bit of a key that is cut to fit the lock. Everything else is the handle you hang things off.'],
    'ternary complex': ['Three things bound together at once — here CRBN, the drug, and PPIL4.', 'A three-way handshake, with the drug as the person holding both other hands.'],
    'PPIL4': ['Peptidyl-prolyl isomerase-like 4 — a spliceosome-associated enzyme. The protein this project is trying to get destroyed.', 'The target on the wall; everything else is the mechanism for throwing the dart.'],
    'peptidyl-prolyl isomerase': ['An enzyme that flips proline residues in a protein chain between two shapes, helping the chain fold or switch conformation.', 'A hinge-flipper: it lets one joint in a long chain snap between two positions.'],
    'spliceosome': ['The molecular machine that cuts introns out of freshly made RNA and joins the remaining pieces together.', 'A film editor cutting out unwanted footage and splicing the good takes into one reel.'],
    'pre-mRNA splicing': ['Removing the non-coding stretches from a freshly transcribed RNA and joining what remains, before it can be used to make protein.', 'Editing the raw footage down to the final cut.'],
    'RRM domain': ['RNA-recognition motif — a common protein fold that grips RNA. PPIL4’s RRM is the surface drug-bound CRBN latches onto.', 'A standard-issue gripper hand, found bolted onto many RNA-handling proteins.'],
    'DepMap': ['A public dataset recording what happens to hundreds of cancer cell lines when each gene is switched off one at a time.', 'A giant table of "remove this part, see if the machine still runs".'],
    'co-dependency': ['When two genes’ knockout effects track each other across many cell lines, hinting they work in the same process.', 'Two employees who are always off sick on the same days — probably on the same team.'],
    'common-essential': ['A gene almost every cell line needs to survive, healthy or cancerous. Hard to exploit for a selective drug.', 'Cutting the mains power: it stops the factory, but it stops every factory.'],
    'AlphaFold': ['A neural network that predicts a protein’s 3D shape from its sequence. Confident in structured regions, unreliable in floppy ones.', 'A very well-read guesser who has seen every structure ever solved — and still shrugs at the wobbly bits.'],
    'docking': ['Computationally trying many ways one molecule could sit against another, and scoring which fit best.', 'Trying every way a key might go into a lock, and rating each attempt.'],
    'HADDOCK score': ['A weighted energy score for a docked complex. More negative is more favourable. It ranks models against each other; it is not a real binding energy.', 'A judge’s score out of ten — useful for ordering the entries, not a physical measurement.'],
    'restraint': ['An instruction given to the docking program about which parts should end up near each other, without specifying exactly how.', 'Telling two people to stand near the door, rather than painting footprints on the floor.'],
    'buried interface': ['How much protein surface stops touching water when two proteins bind. A bigger buried area usually means a more substantial contact.', 'How much of two palms actually touch when you clasp hands.'],
    'cluster': ['A group of predicted structures that are all essentially the same arrangement. If most predictions land in one cluster, the method agreed with itself.', 'If 80 of 100 people sketch the same map, that agreement is the cluster.'],
    'funnel': ['The shape of a docking search: many rough starting poses narrowed down to a few refined ones. A "convergent" funnel means they agree.', 'A talent contest that narrows thousands of auditions to one winner — and you trust it more if the finalists all look alike.'],
    'force field': ['The set of rules and numbers a simulation uses for how atoms attract, repel and bond.', 'The physics engine in a video game.'],
    'van der Waals': ['The weak attraction between atoms that are close together but not bonded.', 'Static cling.'],
    'RMSD': ['Root-mean-square deviation — the average distance between matching atoms of two structures once they are laid on top of each other. Lower means more alike.', 'Overlaying two photos of the same face and measuring how far apart the eyes, nose and mouth land. 2 Å is a close match; 8 Å is a different arrangement.'],
    'DockQ': ['A single 0–1 score for how closely a predicted complex matches a known one, combining three separate measures. 0.23 and above counts as "acceptable".', 'One overall grade rolled up from three separate exam papers.'],
    'native contacts': ['Of all the residue-to-residue touches in the real structure, the fraction the model reproduces.', 'If the real complex is a handshake, this asks how many of the same fingers are touching.'],
    'CAPRI': ['A long-running community benchmark for predicting protein complexes. Its thresholds are where "acceptable" gets its meaning.', 'The agreed exam board — so a grade means the same thing to everyone.'],
    'co-crystal': ['A crystal containing a protein with a small molecule bound inside it, so the drug’s exact position is measured rather than guessed.', 'A photograph of the key actually sitting in the lock.'],
    'heavy atom': ['Any atom in a molecule except hydrogen. Used here as a rough measure of size.', 'Counting the bricks in a model and ignoring the studs.'],
    'constitutional isomer': ['Two molecules with exactly the same atoms but connected differently — same formula, different molecule.', 'Same Lego bricks, different model. The parts list cannot tell them apart.'],
    'SMILES': ['A line of text that encodes a molecule’s exact structure, so it can be sent, searched and rebuilt without a drawing.', 'A molecule’s spelling.'],
    'InChIKey': ['A fixed-length fingerprint computed from a structure. Two molecules share one only if they are the same molecule.', 'A chemical ISBN.'],
    'scaffold split': ['Splitting data so molecules sharing a core structure never appear in both training and test sets.', 'Examining a student on a topic they have never seen, not a reworded homework problem.'],
    'random-forest': ['A machine-learning model that averages the votes of many simple decision trees.', 'Polling a crowd of rule-followers and taking the majority answer.'],
    'noise floor': ['The score reached by something known not to work. Anything at or above it cannot be distinguished from useless.', 'The hiss on a recording. A sound quieter than the hiss might as well not be there.'],
    'ChEMBL': ['A public database of drug-like molecules and their measured biological activities.', 'A library catalogue of things chemists have already tried, and what happened.'],
    'CAS number': ['A unique registry ID assigned to a known chemical substance. A molecule nobody has registered does not have one.', 'A passport number. New compounds have not been issued one yet.'],
    'PDB': ['The Protein Data Bank — the public archive of experimentally determined 3D structures. 9DWV is the entry for the real CRBN–FPFT-2216–PPIL4 complex.', 'The public library of solved molecular shapes.']
  };

  var SKIP_TAGS = /^(SCRIPT|STYLE|CODE|PRE|TEXTAREA|SVG|CANVAS|NOSCRIPT|BUTTON)$/;
  var SKIP_CLOSEST = '.chart, .c-smiles, .gl, .side, table, .mol2d, summary';

  function esc(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

  // Longest first, so "E3 ubiquitin ligase" wins over "ubiquitin".
  var keys = Object.keys(TERMS).sort(function (a, b) { return b.length - a.length; });
  var pattern = new RegExp('\\b(?:' + keys.map(esc).join('|') + ')(?=s\\b|\\b)', 'gi');

  var seenBySection = new WeakMap();
  function sectionOf(node) {
    var el = node.parentElement;
    while (el && el.tagName !== 'SECTION') el = el.parentElement;
    return el || document.body;
  }

  function lookup(text) {
    var lower = text.toLowerCase();
    for (var i = 0; i < keys.length; i++) {
      if (keys[i].toLowerCase() === lower) return keys[i];
    }
    for (var j = 0; j < keys.length; j++) {
      if (lower.indexOf(keys[j].toLowerCase()) === 0) return keys[j];
    }
    return null;
  }

  function annotate() {
    var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode: function (node) {
        if (!node.nodeValue || node.nodeValue.length < 3) return NodeFilter.FILTER_REJECT;
        var p = node.parentElement;
        if (!p || SKIP_TAGS.test(p.tagName)) return NodeFilter.FILTER_REJECT;
        if (p.closest(SKIP_CLOSEST)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    var targets = [], n;
    while ((n = walker.nextNode())) targets.push(n);

    targets.forEach(function (node) {
      var text = node.nodeValue;
      pattern.lastIndex = 0;
      if (!pattern.test(text)) return;
      pattern.lastIndex = 0;

      var sec = sectionOf(node);
      var seen = seenBySection.get(sec);
      if (!seen) { seen = new Set(); seenBySection.set(sec, seen); }

      var frag = document.createDocumentFragment(), last = 0, m, used = false;
      while ((m = pattern.exec(text))) {
        var key = lookup(m[0]);
        if (!key || seen.has(key)) continue;
        seen.add(key);
        used = true;
        frag.appendChild(document.createTextNode(text.slice(last, m.index)));
        var mark = document.createElement('span');
        mark.className = 'gl';
        mark.tabIndex = 0;
        mark.setAttribute('role', 'button');
        mark.setAttribute('aria-label', m[0] + ' — show definition');
        mark.dataset.term = key;
        mark.textContent = m[0];
        frag.appendChild(mark);
        last = m.index + m[0].length;
      }
      if (!used) return;
      frag.appendChild(document.createTextNode(text.slice(last)));
      node.parentNode.replaceChild(frag, node);
    });
  }

  /* ---- the popup ---------------------------------------------------- */
  var pop, current;

  function build() {
    pop = document.createElement('div');
    pop.className = 'gl-pop';
    pop.id = 'gl-pop';
    pop.setAttribute('role', 'tooltip');
    pop.hidden = true;
    pop.innerHTML = '<b class="gl-term"></b><p class="gl-def"></p>' +
                    '<p class="gl-ana"><span>Think of it as</span></p>';
    document.body.appendChild(pop);
  }

  function show(el) {
    var entry = TERMS[el.dataset.term];
    if (!entry) return;
    if (!pop) build();
    current = el;
    pop.querySelector('.gl-term').textContent = el.dataset.term;
    pop.querySelector('.gl-def').textContent = entry[0];
    var ana = pop.querySelector('.gl-ana');
    while (ana.lastChild && ana.lastChild.nodeType === 3) ana.removeChild(ana.lastChild);
    ana.appendChild(document.createTextNode(' ' + entry[1]));
    pop.hidden = false;
    el.setAttribute('aria-describedby', 'gl-pop');

    // Position above the term, flipping below when there is no room, and
    // clamped so a term near the edge does not push the card off-screen.
    var r = el.getBoundingClientRect();
    pop.style.left = '0px'; pop.style.top = '0px';
    var pw = pop.offsetWidth, ph = pop.offsetHeight, pad = 10;
    var left = r.left + r.width / 2 - pw / 2;
    left = Math.max(pad, Math.min(left, window.innerWidth - pw - pad));
    var above = r.top - ph - 12;
    var top = above > pad ? above : r.bottom + 12;
    pop.classList.toggle('below', above <= pad);
    pop.style.left = (left + window.scrollX) + 'px';
    pop.style.top = (top + window.scrollY) + 'px';
  }

  function hide() {
    if (!pop || pop.hidden) return;
    pop.hidden = true;
    if (current) current.removeAttribute('aria-describedby');
    current = null;
  }

  function bind() {
    document.addEventListener('mouseover', function (e) {
      var t = e.target.closest && e.target.closest('.gl');
      if (t) show(t); else if (!e.target.closest('.gl-pop')) hide();
    });
    document.addEventListener('focusin', function (e) {
      var t = e.target.closest && e.target.closest('.gl');
      if (t) show(t); else hide();
    });
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape') hide(); });
    // Touch: a tap should open it, and the same tap must not immediately scroll past.
    document.addEventListener('click', function (e) {
      var t = e.target.closest && e.target.closest('.gl');
      if (t) { e.preventDefault(); current === t ? hide() : show(t); }
      else if (!e.target.closest('.gl-pop')) hide();
    });
    window.addEventListener('scroll', hide, { passive: true });
    window.addEventListener('resize', hide);
  }

  function init() { annotate(); bind(); }
  if (document.readyState !== 'loading') init();
  else document.addEventListener('DOMContentLoaded', init);
})();
